# Package Configuration

set(PKG_NAME)
set(PKG_VERSION)
set(PKG_LICENSE)
set(PKG_APP_GUI)
set(PKG_MANUAL_DIR)
set(PKG_DOXYGEN_SOURCE)
set(PKG_DOXYGEN_EXCLUDES)

set(PKG_VENDOR)
set(PKG_BRIEF_SUMMARY)
set(PKG_REPO)
set(PKG_BUG_REPORT)
set(PKG_MAINTAINER_EMAIL)
set(PKG_LOGO)
set(PKG_DOC_HELP)

set(PKG_SOURCE_EXCLUDES)
