#!/usr/bin/env bash

REPO_VCS="GIT";
REPO_DIR="$(git rev-parse --show-toplevel)";
VS_VFILE="${REPO_DIR}/Version";

VS_MAJOR="XMAKE_MAJOR_VERSION=";
VS_MINOR="XMAKE_MINOR_VERSION=";
VS_PATCH="XMAKE_PATCH_VERSION=";
VS_TWEAK="XMAKE_TWEAK_VERSION=";
