#BUILD_TYPE ?= Debug
#BUILD_TYPE ?= Release

#BUILD_CMD ?= ninja
#GENERATOR ?= 'Ninja'

#BUILD_CMD ?= $(MAKE)
#GENERATOR ?= 'Unix Makefiles'

#BUILD_DIR ?= $(SOURCE_DIR)/build
#INSTALL_PREFIX ?= $(BUILD_DIR)/usr

#DEPS_BUILD_TYPE ?= Release
#DEPS_ROOT_DIR ?= $(SOURCE_DIR)/.deps

#CMAKE_PROG ?=
#CMAKE_ARGS += ...
#EXTRA_CMAKE_ARGS += ...

#GIT_PROG :=
#MAKE_PROG :=

# STRIP_PROG, STRIP_ARGS
# EUSTRIP_PROG, EUSTRIP_ARGS
# DOXYGEN_PROG, DOXYGEN_ARGS
# CPPCHECK_PROG, CPPCHECK_ARGS
# => CPPCHECK17_PROG, CPPCHECK18_PROG
